version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: rides
      POSTGRES_USER: ride_app
      POSTGRES_PASSWORD: psd-ride-db
    ports:
      - "5432:5432"
    volumes:
      - ./initdb/setup.sql:/docker-entrypoint-initdb.d/01_setup.sql
      - ./initdb/create-tables.sql:/docker-entrypoint-initdb.d/01_create-tables.sql  
