version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres-ride:
    image: postgres:latest
    container_name: postgres-db-ride
    environment:
      POSTGRES_DB: rides
      POSTGRES_USER: ride_app
      POSTGRES_PASSWORD: psd-ride-db
    ports:
      - "5432:5432"
    volumes:
      - ./ride/initdb/setup.sql:/docker-entrypoint-initdb.d/01_setup.sql
      - ./ride/initdb/create-tables.sql:/docker-entrypoint-initdb.d/01_create-tables.sql

  postgres-account:
    image: postgres:latest
    container_name: postgres-db-account
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: account
      POSTGRES_PASSWORD: psd-account-db
    ports:
      - "5433:5432"
    volumes:
      - ./account/initdb/setup.sql:/docker-entrypoint-initdb.d/01_setup.sql
      - ./account/initdb/create-tables.sql:/docker-entrypoint-initdb.d/01_create-tables.sql  